# CMD sets the command and its parameters to be executed by default after the container is started.
# However CMD can be replaced by docker run command with command line parameters 

#The CMD directive allows user to specify the default command executed by the container. This command runs when the container starts and no other command is specified for docker run .


FROM ubuntu:18.04
RUN apt-get install python3
CMD echo "Hello world"


